# Configuration for MyApolloPlugin

staff-mode:
  enabled: true
  # (No additional settings for staff mode toggle)

nametag:
  enabled: true
  # Define up to 3 lines for the Apollo nametag module (one above, one as name, and one/two below).
  # Use PlaceholderAPI placeholders to include dynamic info (e.g. team, stats).
  lines:
    - "&7Team: %betterteams_name%"         # Line above name: team name (gray color)
    - "%player_displayname%"              # Main name line (will show player's display name with any color codes)
    - "&7Balance: $%betterteams_balance%" # Line below name: team balance (if BetterTeams has a balance system)
    # - "&7Points: %betterteams_score%"   # (example alternative line for team score, if applicable)

richpresence:
  enabled: true
  update-interval: 100        # Update interval in ticks (e.g. 100 ticks = 5 seconds)
  gameName: "MyServer"        # e.g. Server or game mode name to display
  gameVariantName: "%player_world%"   # e.g. world or mode variant (using placeholder for world name)
  gameState: "Online"         # e.g. current game state (static or use placeholder)
  playerState: ""             # e.g. what the player is doing (leave blank if not used)
  mapName: "X:%player_x% Y:%player_y% Z:%player_z%"  # Format to show coordinates
  subServerName: ""           # e.g. sub-server or map name if applicable
  showTeam: true              # Whether to show team size info in rich presence
