name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers workflow on version tags like v1.0.0

permissions:
  contents: write  # Grants permission to create releases and upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar  # Adjust the path if your JAR is located elsewhere
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
